# Generated by Django 5.1.1 on 2024-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_new_location_new_location_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_URL', models.URLField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CONF', 'Conference'), ('WEB', 'Webinar'), ('WORK', 'Workshop'), ('MEET', 'Meeting')], default='CONF', max_length=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_virtual', models.BooleanField(default=False)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='new',
            old_name='attact',
            new_name='attract',
        ),
    ]
