# Generated by Django 5.1.1 on 2024-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_rename_attact_new_attract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='new',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
