# Generated by Django 5.1.1 on 2024-10-08 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('inquiry', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Virtual Receptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
